"""Copy of pymatgen

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tuf9fD66xS3qw8Ax-GJ0V2egTXfxFtjA
"""

import pymatgen

import os
import json
import ijson
import csv
import bz2
import itertools
import pickle
from pprint import pprint
from tqdm import tqdm

"""##MPTrj Dataset
**How to do this for a very large dataset?**
<br>
https://figshare.com/articles/dataset/Materials_Project_Trjectory_MPtrj_Dataset/23713842?file=41619375


"""

file = r"D:\MPtrj_2022.9_full.json"

# Split json via: https://pythonspeed.com/articles/json-memory-streaming/


# Open the json file using ijson
# print a couple of lines from the json file in the pretty string format

with open(file, 'rb') as data:
    print("loaded data")
    parser = ijson.items(data,'structure')
    for i, item in tqdm(enumerate(parser), desc="Processing items", unit="item"):
        print(f"Item {i + 1}:")
        print(item)
        print(len(item))
        try:
            print(type(item[2]))
        except:
            continue
        print("-" * 40)  # Separator for readability
        if i >= 9:  # Will print 10 items (0-9)
            break

